apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-env-vars" (include "config-server.fullname" .) }}
  namespace: {{ .Release.Namespace }}
data:
  SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: {{ .Values.gitRepo.searchFolders  | quote }}
  {{- if .Values.localRepo.enabled }}
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: {{ .Values.pv.mountDir | quote }}
  {{- else }}
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: {{ .Values.gitRepo.uri | quote }}
  {{- end }}
  SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: {{ .Values.gitRepo.username | quote  }}