## This file contains various secrets that are needed by different mosip modules. The reason for defining
## them here (and not while module installation) is as follows:
## 1. These secrets are made available to modules via config property files (defined in *.properties) 
## 2.  Config server is installed before MOSIP modules
## Some of them may not be used as the corresponding modules may not be installed.
## For websub hub secret refer to: https://www.w3.org/TR/websub/#subscriber-sends-subscription-request

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-various" (include "config-server.fullname" .) }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ida-websub-authtype-callback-secret: {{ randAlphaNum 16 | b64enc | quote }}
  ida-websub-credential-issue-callback-secret: {{ randAlphaNum 16 | b64enc | quote }}
  ida-websub-partner-service-callback-secret: {{ randAlphaNum 16 | b64enc | quote }}
  ida-websub-ca-certificate-callback-secret: {{ randAlphaNum 16 | b64enc | quote }}
  ida-websub-hotlist-callback-secret: {{ randAlphaNum 16 | b64enc | quote }}
  ida-websub-masterdata-templates-callback-secret: {{ randAlphaNum 16 | b64enc | quote }}
  ida-websub-masterdata-titles-callback-secret: {{ randAlphaNum 16 | b64enc | quote }}
  idrepo-websub-vid-credential-update-secret: {{ randAlphaNum 16 | b64enc | quote }}
  mosip-kernel-tokenid-uin-salt: {{ randAlphaNum 16 | b64enc | quote }}
  mosip-kernel-tokenid-partnercode-salt: {{ randAlphaNum 16 | b64enc | quote }}
  print-websub-hub-secret: {{ randAlphaNum 16 | b64enc | quote }}
  resident-websub-authtype-status-secret: {{ randAlphaNum 16 | b64enc | quote  }}
  resident-websub-auth-transaction-status-secret: {{ randAlphaNum 16 | b64enc | quote  }}
