apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data:
  maven-metadata.xml: |-
   <metadata>
     <groupId>io.mosip.registration</groupId>
     <artifactId>registration-services</artifactId>
     <versioning>
       <versions>
          <version>{{ .Values.regclient.version }}</version>
       </versions>
     <lastUpdated>20200729125958</lastUpdated>
     </versioning>
   </metadata>



