apiVersion: v2
name: compliance-toolkit-ui
description: A Helm chart for compliance-toolkit-ui
type: application
version: 12.0.2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - compliance-toolkit-ui
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
