apiVersion: v2
name: opencrvs-mediator
description: A Helm chart for mosip-opencrvs mediator.
type: application
version: 12.0.1
appVersion: ""
home: https://mosip.io
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
   - bitnami-common
  version: 1.x.x
keywords:
 - mosip
 - mosip-opencrvs-mediator
 - opencrvs-mediator
 - opencrvs
maintainers:
 - email: info@mosip.io
   name: MOSIP
