apiVersion: v2
name: ida-kyc
description: A Helm chart for MOSIP IDA module 
type: application
version: 1.1.5
appVersion: "1.1.5"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - ida-kyc
  - ida
maintainers:
  - email: info@mosip.io
    name: MOSIP 
