apiVersion: v2
name: vid
description: A Helm chart for MOSIP IDRepo VID Service
type: application
version: 1.1.5
appVersion: "1.1.5"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - vid
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP 
