## Config map to insert a landing index.html page in the docker.  This may be removed later if the same is done while building the docker.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-index
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <title>MOSIP {{ .Values.landing.name }}</title> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
    body, h1, h2, h3, h4, h5, h6  {
      font-family: "Trebuchet MS", Tahoma, sans-serif;
    }
    </style>
    <body>
    <header class="w3-container w3-teal w3-center">
      <div class="w3-padding">
        <img src="https://mosip.github.io/mosip-helm/mosip_logo.png" width="50px">
        <h3>MOSIP Deployment</h3>
        <h2><b>{{ .Values.landing.name }}</b></h2>
        <h3>Version: {{ .Values.landing.version }}</h3>
      </div>
    </header>
    <div class="w3-container w3-padding-16">
      <!-- row 1 -->
      <div class="w3-row-padding w3-padding-16">
        <div class="w3-col l2 w3-center"><p></p></div> 
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.activemq }}">
            <img src="https://activemq.apache.org/assets/img/activemq_logo_white_vertical.png" style="height:80px">
            <p>ActiveMQ</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.kafka }}">
            <img src="http://svn.apache.org/repos/asf/kafka/site/logos/kafka-logo-no-text.png" style="height:80px">
            <p>Kafka</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.keycloak }}">
            <img src="https://www.keycloak.org/resources/images/keycloak_icon_512px.svg" style="height:80px">
            <p>Keycloak</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.regclient }}">
          <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/reg-client-orig.png" style="height:80px">
          <p>Registration Client</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center"><p></p></div> 
      </div>
    
      <!-- row 2 -->
      <div class="w3-row-padding w3-padding-16">
        <div class="w3-col l2 w3-center"><p></p></div> 
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.kibana }}">
            <img src="https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt4466841eed0bf232/5d082a5e97f2babb5af907ee/logo-kibana-32-color.svg" style="height:80px">
            <p>Kibana</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.prereg }}/pre-registration-ui/">
          <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/pre-reg-login.png" style="height:80px">
          <p>Pre-registration</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.minio }}">
            <img src="https://min.io/resources/img/logo/MINIO_Bird.png" style="height:80px">
            <p>MinIO</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.admin }}">
          <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/admin-home.png" style="height:80px">
          <p>Admin</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center"><p></p></div> 
      </div>
    
      <!-- row 3 -->
      <div class="w3-row-padding w3-padding-16">
        <div class="w3-col l2 w3-center"><p></p></div> 
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.pmp }}">
          <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/pms-home-page.png" style="height:80px">            <p>PMP</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.api }}/.well-known/">
            <p>.well-known</p>
          </a>
          <a href="https://{{ .Values.landing.api }}/inji/">
            <p>INJI</p>
          </a>
          <a href="https://{{ .Values.landing.api }}/mosip-certs/">
            <p>MOSIP certs</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.compliance }}">
          <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/compliance-home-page.png" style="height:80px">            <p>COMPLIANCE</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.resident }}">
             <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/resident-home-page.png" style="height:80px">
          <p>resident</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center"><p></p></div> 
      </div>
      
      <!-- row 4 -->
      <div class="w3-row-padding w3-padding-16">
        <div class="w3-col l2 w3-center"><p></p></div> 
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.esignet }}">
             <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/esignet-home-page.png" style="height:80px">
             <p>esignet</p>
          </a>
        </div>
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.healthservices }}">
          <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/healthservices.png" style="height:80px">
          <p>Healthservices</p>
          </a>
        </div>
    {{- if .Values.landing.smtp }}
        <div class="w3-col l2 w3-center">
          <a href="https://{{ .Values.landing.smtp }}">
             <img src="https://raw.githubusercontent.com/mosip/documentation/1.2.0/docs/_images/smtp-home-page.png" style="height:80px">
             <p>SMTP</p>
          </a>
        </div>
    {{- end }}
        <div class="w3-col l2 w3-center"><p></p></div>
      </div>
    
      <!-- row 5 -->
      <div class="w3-row-padding w3-padding-16">
        <div class="w3-col l4 w3-center"><p></p></div> 
        <div class="w3-col l4 w3-left">
          <div class="w3-panel w3-khaki w3-round-large">
             <table class="w3-table">
               <tr>
                 <td>External API</td>
                 <td class="w3-monospace">https://{{ .Values.landing.api }}</td>
               </tr>
               <tr>
                 <td>Internal API</td>
                 <td class="w3-monospace">https://{{ .Values.landing.apiInternal }}</td>
               </tr>
               <tr>
                 <td>
                   <img src="https://www.clipartmax.com/png/full/242-2423721_logo-postgresql.png" height="30px">
                 </td>
                 <td class="w3-monospace">{{ .Values.landing.postgres.host }}:{{ .Values.landing.postgres.port }}</td>
               </tr>
             </table>
          </div>
        <div class="w3-col l4 w3-center"><p></p></div> 
      </div>
    
    </div>
    <!-- footer -->
    <footer class="w3-container w3-teal w3-center">
      <div class="w3-padding">
        <a href="https://mosip.io">MOSIP Website</a> &nbsp;&nbsp;&nbsp; 
        <a href="https://docs.mosip.io">MOSIP Docs</a>
      </div>
    </footer>
    </body>
    </html>

