{{- if .Values.databases.mosip_credential.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: db-credential-init-job
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "postgres-init.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: db-credential-init-job
        sidecar.istio.io/inject: "false"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-init.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jobSecurityContext | nindent 8 }}
      restartPolicy: Never  # This is one time job
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SU_USER_PWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.databases.mosip_credential.su.secret.name }}
                key: {{ .Values.databases.mosip_credential.su.secret.key }}

          - name: DBUSER_PWD
            valueFrom:
              secretKeyRef:
                name: db-common-secrets
                key: db-dbuser-password

          envFrom:
              - configMapRef:
                  name: db-credential-init-env-config
{{- end }}
