apiVersion: v2
name: regproc-abishandler
description: A Helm chart for MOSIP Registration Processor ABIS Handler stage
type: application
version: 1.1.5
appVersion: "1.1.5"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - regproc-abishandler
  - regproc
maintainers:
  - email: info@mosip.io
    name: MOSIP 
