apiVersion: v2
name: prereg-ui
description: A Helm chart for MOSIP Pre-registration UI
type: application
version: 12.0.1-B2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - prereg-ui
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
