apiVersion: v2
name: softhsm
description: A Helm chart for MOSIP Softhsm module
type: application
version: 12.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - softhsm
  - hsm
maintainers:
  - email: info@mosip.io
    name: MOSIP
