apiVersion: v2
name: reporting-init
description: A Helm chart for MOSIP Reporting Initialization.
type: application
version: 12.0.1
appVersion: ""
maintainers:
  - email: info@mosip.io
    name: MOSIP
