apiVersion: v2
name: kernel-keygen
description: A Helm chart to generate keys for Kernel
type: application
version: 1.1.5
appVersion: "1.1.5"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - keymanager 
  - keygen
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP 
