apiVersion: v2
name: keymanager
description: A Helm chart for MOSIP Keymanager module
type: application
version: 12.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - keymanager
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
