apiVersion: v2
name: print-service
description: A Helm chart for sample Print Service
type: application
version: 12.0.1-B2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - print-service
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
