## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Add labels to all the deployed resources
##
commonLabels:
  app.kubernetes.io/component: postgres

## Add annotations to all the deployed resources
##
commonAnnotations: {}

## Kubernetes Cluster Domain
##
clusterDomain: cluster.local

## Extra objects to deploy (value evaluated as a template)
##
extraDeploy: []

## Number of nodes
##
replicaCount: 1

image:
  registry: docker.io
  repository: mosipdev/data-archive
  tag: develop

  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

##
# existingConfigmap:

## Command and args for running the container (set to default if not set). Use array form
##
command: []
args: []

## Deployment pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []

## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 3500Mi
  requests:
    cpu: 1000m
    memory: 3500Mi

# additionalResources:
  ## Specify any JAVA_OPTS string here. These typically will be specified in conjunction with above resources
  ## Example: java_opts: "-Xms500M -Xmx500M"
  #javaOpts: "-Xms2600M -Xmx2600M"

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
## Clamav container already runs as 'mosip' user, so we may not need to enable this
containerSecurityContext:
  enabled: false
  runAsUser: mosip
  runAsNonRoot: true

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  enabled: false
  fsGroup: 1001

## Pod affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAffinityPreset: ""

## Pod anti-affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAntiAffinityPreset: soft

## Node affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
## Allowed values: soft, hard
##
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  ##
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []

## Affinity for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
## Some common set of users are created across all postgres servers with same password.  TODO: change this later.
## These user names are currently hardcoded in the sql scripts, so can't change from here.

nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Pod extra labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Annotations for server pods.
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

##  pods' priority.
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
# priorityClassName: ""

## lifecycleHooks for the  container to automate configuration before or after startup.
##
lifecycleHooks: {}

## Custom Liveness probes for
##
customLivenessProbe: {}

## Custom Rediness probes
##
customReadinessProbe: {}

## Update strategy - only really applicable for deployments with RWO PVs attached
## If replicas = 1, an update can get "stuck", as the previous pod remains attached to the
## PV, and the "incoming" pod can never start. Changing the strategy to "Recreate" will
## terminate the single previous pod, so that the new, incoming pod can attach to the PV
##
updateStrategy:
  type: RollingUpdate

## Additional environment variables to set
## Example:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []

## ConfigMap with extra environment variables
##
# extraEnvVarsCM:
  # - s3

## Secret with extra environment variables
##
# extraEnvVarsSecret:
 # - s3

## Extra volumes to add to the deployment
##
extraVolumes: []

## Extra volume mounts to add to the container
##
extraVolumeMounts: []

## Add init containers to the  pods.
## Example:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
initContainers: {}

## Add sidecars to the  pods.
## Example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: {}

persistence:
  enabled: false
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack).
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  ## ReadWriteMany not supported by AWS gp2
  storageClass:
  accessModes:
    - ReadWriteOnce
  size: 10M
  existingClaim:
  # Dir where config and keys are written inside container
  mountDir:

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: "10"
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    pullSecrets: []
    ##   - myRegistryKeySecretName
  ## Init containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    ##
    # limits: {}
    ##   cpu: 100m
    ##   memory: 128Mi
    ##
    # requests: {}
    ##   cpu: 100m
    ##   memory: 128Mi
    ##

## Specifies whether RBAC resources should be created
##
rbac:
  create: true

## Specifies whether a ServiceAccount should be created
##
serviceAccount:
  create: true
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name:

## Admin swagger should have only internal access. Hence linked to internal gateway
istio:
  enabled: false
  gateways:
    - istio-system/internal

crontime: "0 4 * * *"    ## run cronjob every day at 4 AM in GMT which is 9.30 AM in IST (time hr: 0-23 )

databases:
  archive_db:
    db_name: "mosip_archive"
    host: "api-internal.sandbox.xyz.net"
    port: 5432
    su_user: "postgres"
    su_user_pwd: ""
    db_pwd: ""
    dml: 0
    archivehost: "api-internal.sandbox.xyz.net"
    archiveport: 5432
    archiveuname: "archiveuser"
    archive_dbname: "mosip_archive"
    archive_schemaname: "archive"
    archive_db_password: ""
  source_db:
    provide_db_names_to_archive: "AUDIT,CREDENTIAL,IDA"
    source_audit_host: "api-internal.sandbox.xyz.net"
    source_audit_port: 5432
    source_audit_uname: "audituser"
    source_audit_dbname: "mosip_audit"
    source_audit_schemaname: "audit"
    source_audit_db_pass: ""
    source_credential_host: "api-internal.sandbox.xyz.net"
    source_credential_port: 5432
    source_credential_uname: "credentialuser"
    source_credential_dbname: "mosip_credential"
    source_credential_schemaname: "credential"
    source_credential_db_pass: ""
    source_esignet_host: "api-internal.sandbox.xyz.net"
    source_esignet_port: 5432
    source_esignet_uname: "esignetuser"
    source_esignet_dbname: "mosip_esignet"
    source_esignet_schemaname: "esignet"
    source_esignet_db_pass: ""
    source_ida_host: "api-internal.sandbox.xyz.net"
    source_ida_port: 5432
    source_ida_uname: "idauser"
    source_ida_dbname: "mosip_ida"
    source_ida_schemaname: "ida"
    source_ida_db_pass: ""
    source_idrepo_host: "api-internal.sandbox.xyz.net"
    source_idrepo_port: 5432
    source_idrepo_uname: "idrepouser"
    source_idrepo_dbname: "mosip_idrepo"
    source_idrepo_schemaname: "idrepo"
    source_idrepo_db_pass: ""
    source_kernel_host: "api-internal.sandbox.xyz.net"
    source_kernel_port: 5432
    source_kernel_uname: "kerneluser"
    source_kernel_dbname: "mosip_kernel"
    source_kernel_schemaname: "kernel"
    source_kernel_db_pass: ""
    source_master_host: "api-internal.sandbox.xyz.net"
    source_master_port: 5432
    source_master_uname: "masteruser"
    source_master_dbname: "mosip_master"
    source_master_schemaname: "master"
    source_master_db_pass: ""
    source_pms_host: "api-internal.sandbox.xyz.net"
    source_pms_port: 5432
    source_pms_uname: "pmsuser"
    source_pms_dbname: "mosip_pms"
    source_pms_schemaname: "pms"
    source_pms_db_pass: ""
    source_regprc_host: "api-internal.sandbox.xyz.net"
    source_regprc_port: 5432
    source_regprc_uname: "regprcuser"
    source_regprc_dbname: "mosip_regprc"
    source_regprc_schemaname: "regprc"
    source_regprc_db_pass: ""
    source_resident_host: "api-internal.sandbox.xyz.net"
    source_resident_port: 5432
    source_resident_uname: "residentuser"
    source_resident_dbname: "mosip_resident"
    source_resident_schemaname: "resident"
    source_resident_db_pass: ""
