apiVersion: v1
kind: ConfigMap
metadata:
  name: wellknown-cm
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data:
  public-key.json: |-
    {
      "@context": "https://w3id.org/security/v2",
      "type": "RsaVerificationKey2018",
      "id": "https://{{ .Values.mosipfileserver.host }}/.well-known/public-key.json",
      "controller": "https://{{ .Values.mosipfileserver.host }}/.well-known/controller.json",
      "publicKeyPem": "replace-public-key"
    }
  ida-public-key.json: |-
    {
      "@context": "https://w3id.org/security/v2",
      "type": "RsaVerificationKey2018",
      "id": "https://{{ .Values.mosipfileserver.host }}/.well-known/ida-public-key.json",
      "controller": "https://{{ .Values.mosipfileserver.host }}/.well-known/ida-controller.json",
      "publicKeyPem": "replace-public-key"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 8 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
  {{- end }}
data:
  {{- if .Values.mosipfileserver.configmaps }}
  {{- range $key, $value := .Values.mosipfileserver.configmaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
