apiVersion: v2
name: status-check
description: A Helm chart to deploy status
type: application
version: 12.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - status
maintainers:
  - email: info@mosip.io
    name: MOSIP
