apiVersion: v2
name: keycloak-init
description: A Helm chart for Kubernetes to initialize Keycloak  (updating for test)
type: application
version: 1.1.5
appVersion: 1.1.5
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x

home: https://mosip.io
keywords:
  - keycloak
  - access-management
maintainers:
  - email: info@mosip.io
    name: MOSIP 
