apiVersion: v2
name: testrigs-cron
description: A Helm chart to deploy dslorchestrator to test working of MOSIP modules
type: application
version: 12.0.2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - testrigs-cron
maintainers:
  - email: info@mosip.io
    name: MOSIP
