kind: ServiceAccount
apiVersion: v1
metadata:
    name: {{ template "apitestrig.sa.cronjob" . }}
    namespace: {{ .Release.Namespace }}
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: Role
metadata:
    name: {{ template "apitestrig.role.cronjob" . }}
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups: ["apps", "extensions"]
      resources: ["deployments"]
      resourceNames: ["apitestrig-prereg"]
      verbs: ["get", "patch", "list", "watch"] # "list" and "watch" are only needed
                                               # if you want to use `rollout status`
---
# bind the role to the service account
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
    name: {{ template "apitestrig.rolebinding.cronjob" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ template "apitestrig.role.cronjob" . }}
subjects:
    - kind: ServiceAccount
      name: {{ template "apitestrig.sa.cronjob" . }}
      namespace: {{ .Release.Namespace }}