apiVersion: v2
name: packetmanager
description: A Helm chart for MOSIP Packetmanager module 
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - packetmanager
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP 
