apiVersion: v2
name: partner-onboarder
description: A Helm chart for onboarding default partners for MOSIP sandbox.
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - partner-onboarder
  - partners
maintainers:
  - email: info@mosip.io
    name: MOSIP
