apiVersion: v2
name: clamav
description: A Helm chart for Clamav
type: application
version: 12.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - clamav
  - antivirus
  - anti-virus
maintainers:
  - email: info@mosip.io
    name: MOSIP
