apiVersion: v2
name: mosip-file-server
description: A Helm chart to file server application.
type: application
version: 12.0.x-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - mosip-file-server
  - fileserver
maintainers:
  - email: info@mosip.io
    name: MOSIP
