apiVersion: v2
name: postgres-upgrade
description: A Helm chart for Kubernetes to Upgrade various Postgres DBs.
type: application
version: 0.0.1-develop
appVersion: 1.2.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x

home: https://mosip.io
keywords:
  - postgres-upgrade
  - db-upgrade
  - database
maintainers:
  - email: info@mosip.io
    name: MOSIP
