apiVersion: batch/v1
kind: Job
metadata:
  name: masterdata-loader
  labels:
    {{- include "masterdata-loader.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "masterdata-loader.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: masterdata-loader
        sidecar.istio.io/inject: "false"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "masterdata-loader.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jobSecurityContext | nindent 8 }}
      restartPolicy: Never  # This is one time job
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.secret.name }}
                key: {{ .Values.db.secret.key }}

          envFrom:
              - configMapRef:
                  name: env-config
