apiVersion: v2
name: tusd
description: A Helm chart to file server application.
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - tusd
maintainers:
  - email: info@mosip.io
    name: MOSIP
