apiVersion: v2
name: reporting
description: A Helm chart for MOSIP Reporting module.
type: application
version: 1.2.0.1
appVersion: ""
dependencies:
- name: cp-helm-charts
  alias: confluentinc
  repository: "https://confluentinc.github.io/cp-helm-charts/"
  version: ">= 0.6.1"
  condition: confluentinc.enabled
- name: kafka
  alias: bitnami-kafka
  repository: "https://charts.bitnami.com/bitnami"
  version: ">= 14.0.3"
  condition: bitnami-kafka.enabled
- name: elasticsearch
  alias: bitnami-elasticsearch
  repository: "https://charts.bitnami.com/bitnami"
  version: ">= 17.0.0"
  condition: bitnami-elasticsearch.enabled
