apiVersion: v2
name: reporting
description: A Helm chart for MOSIP Reporting module.
type: application
version: 1.1.5
appVersion: "1.1.5"
dependencies:
- name: cp-helm-charts
  alias: confluentinc
  repository: "https://confluentinc.github.io/cp-helm-charts/"
  version: ">= 0.6.1"
- name: kafka
  alias: bitnami-kafka
  repository: "https://charts.bitnami.com/bitnami"
  version: ">= 14.0.3"
